### ISSUE TITLE
Bug: Can't run `ts-bundle-project` on MacOS/Linux

### ISSUE THREAD

**Issue by SierraJC** [ashleydavis/ts-project-bundle#3]
When attempting to run `ts-project-bundle` on MacOS or inside any linux Docker image, the command fails.

```
$ ts-project-bundle --out=dist
env: node\r: No such file or directory
error Command failed with exit code 127.
```

Calling `node node_modules/ts-project-bundle/build/cli.js --out=dist` directly works, but only bypasses the root issue.

This is being caused by the EOL encoding of `node_modules/.bin/ts-project-bundle`.
Changing the file encoding from `CRLF` to `LF` will fix the issue.

**Comment by ashleydavis** [comment]
If you can the line endings and submit a PR I'll be happy to accept.
